----------------
----------------
----------------

-- Criando a tabela ENDERECO
CREATE TABLE ENDERECO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    CEP CHAR(9) NOT NULL,
    LOGRADOURO NVARCHAR(150) NOT NULL,
    COMPLEMENTO NVARCHAR(50) NULL,
    UNIDADE NVARCHAR(80) NULL,
    BAIRRO NVARCHAR(80) NOT NULL,
    LOCALIDADE NVARCHAR(80) NULL,
    UF CHAR(2) NOT NULL,
    ESTADO NVARCHAR(80) NOT NULL,
    REGIAO NVARCHAR(80) NULL,
    IBGE NVARCHAR(10) NULL,
    GIA NVARCHAR(10) NULL,
    DDD CHAR(2) NULL,
    SIAFI NVARCHAR(10) NULL,
    PAIS NVARCHAR(50) DEFAULT 'Brasil'
);


-- Criando a tabela LOG_ENDERECO
CREATE TABLE LOG_ENDERECO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ACAO NVARCHAR(50) NOT NULL,
    DATA_HORA DATETIME,
    OBSERVACAO NVARCHAR(255) NULL,
	ENDERECO_ID INT NOT NULL,
    FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ID)
);



--DROP TABLE ENDERECO;
--DROP TABLE LOG_ENDERECO;



